### ISSUE TITLE
請問支持多選嗎？

### ISSUE THREAD

**Issue by Yanghsuanming** [phaoer/Cascader#2]
![image](https://github.com/phaoer/Cascader/assets/40749214/6ca2c6ba-bc59-4e26-82c1-927256e6f8c5)

**Comment by phaoer** [comment]
在2.0.2已经支持多选模式。
`mode: multiple`
对应的defaultValue应使用二元数组
`defaultValue: [["sichuan", "chengdu", "jinli"]]`
