### ISSUE TITLE
 当一个页面需要展示两个及联选择器时，只允许全局只有一个实例，在同一个实例上更新options  报错。 index.js:464 Uncaught TypeError: Cannot read properties of null (reading 'click')     at t.setValue (index.js:464:20)     at initCascader (index.html:1036:30)     at init (index.html:1046:20)     at HTMLAnchorElement.<anonymous> (index.html:971:17)

### ISSUE THREAD

**Issue by Avicii13579** [phaoer/Cascader#5]
function initCascader(selector, options) {
   
    if (cascaderInstance) {
        if ( this.textContent === 'Claim') {
            cascaderInstance.reset() 
            cascaderInstance.setValue(options.options)
        } else {
            const options2 = [
                            {
                                className: "sichuan",
                                value: "sichuan",
                                label: "1111111",
                                showTitle: true,
                                children: [
                                    {
                                        value: "chengdu",
                                        label: "Chengdu",
                                        children: [
                                            {
                                                value: "1",
                                                label: "Wuhou Shrine",
                                            },
                                            {
                                                value: "jinli",
                                                label: "Jinli Street",
                                            },
                                        ],
                                    },
                                    {
                                        value: "https://www.baidu.com/",
                                        label: "Mianyang",
                                    },
                                    {
                                        value: "zigong",
                                        label: "Zigong",
                                    },
                                ],
                            }]
            cascaderInstance.reset() 
            cascaderInstance.setValue(options2)
        }
    } else {
        cascaderInstance = new Cascader(selector, options);
        cascaderInstance.init();
    }
  
}

function init() {
    var cascader = initCascader("#claims-search", {
				width: 1200,
				placeholder: "please select",
				mode: "single",    //multiple
				options: [
					{
						className: "sichuan",
						value: "sichuan",
						label: "1111111",
						showTitle: true,
						children: [
							{
								value: "chengdu",
								label: "Chengdu",
								children: [
									{
										value: "1",
										label: "Wuhou Shrine",
									},
									{
										value: "jinli",
										label: "Jinli Street",
									},
								],
							},
							{
								value: "https://www.baidu.com/",
								label: "Mianyang",
							},
							{
								value: "zigong",
								label: "Zigong",
							},
						],
					},
					{
						value: "zhejiang",
						label: "Zhejiang",
						children: [
							{
								value: "hangzhou",
								label: "Hangzhou",
								children: [
									{
										value: "xihu",
										label: "West Lake",
									},
								],
							},
						],
					},
					{
						value: "jiangsu",
						label: "Jiangsu",
						disabled: true,
						children: [
							{
								value: "nanjing",
								label: "Nanjing",
							},
						],
					},
					{
						value: "hongkong",
						label: "Hongkong",
					},
				],
				showClear: true,
				defaultValue: ["sichuan", "chengdu", "jinli"],   //multiple [["sichuan", "chengdu", "jinli"]]
				onChange: function (value, labelValue) {
                    // value 输入为 url 
                    // window.location.href = value[value.length - 1];
					console.log(value, labelValue);
				},
				displayRender: function (label) {
					return label.join("~");
				},
			});
}

**Comment by phaoer** [comment]
This issue has been fixed in version 2.0.3

**Comment by phaoer** [comment]
This issue has been fixed in version 2.0.3
